# Generated by Django 4.1.6 on 2023-02-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                  CREATE TRIGGER search_vector_trigger
                  BEFORE INSERT OR UPDATE OF title, description, search_vector
                  ON youtube_video
                  FOR EACH ROW EXECUTE PROCEDURE
                  tsvector_update_trigger(
                    search_vector, 'pg_catalog.english', title, description
                  );

                  UPDATE youtube_video SET search_vector = NULL;
                ''',

            reverse_sql='''
                  DROP TRIGGER IF EXISTS search_vector_trigger
                  ON youtube_video;
                '''
        ),
    ]
