# Generated by Django 4.1.6 on 2023-02-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_video_channel_id_video_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('exhausted', models.BooleanField(default=False)),
            ],
        ),
    ]
